version: '3'
services:
  app:
    platform: linux/arm64
    build:
      context: .
      target: runner
    entrypoint:
      - sh
      - -c
      - cd /com.docker.devenvironments.code
    ports:
      - 1234:1234

